<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>OrderExtractorWorker</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../OrderFlow.Contracts/OrderFlow.Contracts.csproj" />
    </ItemGroup>
</Project>
