name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-pack:
    name: Build & Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --filter "Category!=Integration";

      - name: Pack
        run: dotnet pack -c Release --no-build --no-restore -o ./nupkg -p:Version=0.0.0-ci.${{ github.run_number }}

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: nupkg
          path: ./nupkg
