name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    name: Build & Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --filter "Category!=Integration";

      - name: Pack
        run: dotnet pack -c Release --no-build -o ./nupkg -p:Version=${{ steps.version.outputs.version }}

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: nupkg
          path: ./nupkg

  publish:
    name: Publish to NuGet
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: nupkg
          path: ./nupkg

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: NuGet login
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
